/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Namelesss
 */
public class viewPaciente extends javax.swing.JFrame {

    /**
     * Creates new form viewPaciente
     */
    public viewPaciente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOpcionesMenu = new javax.swing.JPanel();
        lblSolicitarCita = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblConfigCuenta = new javax.swing.JLabel();
        pnlTituloMenu = new javax.swing.JPanel();
        lblTituloMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOpcionesMenu.setBackground(new java.awt.Color(204, 204, 204));
        pnlOpcionesMenu.setName("pnlOpcionesMenu"); // NOI18N

        lblSolicitarCita.setBackground(new java.awt.Color(255, 255, 255));
        lblSolicitarCita.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        lblSolicitarCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSolicitarCita.setText("Solicitar Cita");
        lblSolicitarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSolicitarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSolicitarCita.setName("lblSolicitarCita"); // NOI18N
        lblSolicitarCita.setOpaque(true);
        lblSolicitarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSolicitarCitaMouseClicked(evt);
            }
        });

        lblCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        lblCerrarSesion.setText("Cerrar Sesion");
        lblCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCerrarSesion.setOpaque(true);
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        lblConfigCuenta.setBackground(new java.awt.Color(255, 255, 255));
        lblConfigCuenta.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        lblConfigCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfigCuenta.setText("Configuraciones");
        lblConfigCuenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblConfigCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblConfigCuenta.setOpaque(true);
        lblConfigCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfigCuentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcionesMenuLayout = new javax.swing.GroupLayout(pnlOpcionesMenu);
        pnlOpcionesMenu.setLayout(pnlOpcionesMenuLayout);
        pnlOpcionesMenuLayout.setHorizontalGroup(
            pnlOpcionesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesMenuLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(pnlOpcionesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblConfigCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSolicitarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(lblCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        pnlOpcionesMenuLayout.setVerticalGroup(
            pnlOpcionesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSolicitarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblConfigCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(pnlOpcionesMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 395, -1));

        pnlTituloMenu.setBackground(new java.awt.Color(129, 236, 236));
        pnlTituloMenu.setName("pnlTituloMenu"); // NOI18N
        pnlTituloMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloMenu.setBackground(new java.awt.Color(129, 236, 236));
        lblTituloMenu.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        lblTituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMenu.setText("Menú Paciente");
        lblTituloMenu.setName("lblTituloMenu"); // NOI18N
        pnlTituloMenu.add(lblTituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, 301, 46));

        getContentPane().add(pnlTituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 395, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSolicitarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitarCitaMouseClicked
        viewSolicitarCita jSoliCita = new viewSolicitarCita();
        jSoliCita.setVisible(true);
    }//GEN-LAST:event_lblSolicitarCitaMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblConfigCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigCuentaMouseClicked
        ViewCuenta Cuenta = new ViewCuenta();
        Cuenta.setVisible(true);
    }//GEN-LAST:event_lblConfigCuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblConfigCuenta;
    private javax.swing.JLabel lblSolicitarCita;
    private javax.swing.JLabel lblTituloMenu;
    private javax.swing.JPanel pnlOpcionesMenu;
    private javax.swing.JPanel pnlTituloMenu;
    // End of variables declaration//GEN-END:variables
}
