/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Control.clsHistoriaClinica;
import Control.clsHistoriaClinicaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juan jose
 */
public class viewGenerarHistoria extends javax.swing.JFrame {

    clsHistoriaClinicaDAO daoHistoria = new clsHistoriaClinicaDAO();
    
    /**
     * Creates new form viewGenerarHistoria
     */
    public viewGenerarHistoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGenerarHistoria = new javax.swing.JLabel();
        lblperId = new javax.swing.JLabel();
        lblNumPaciente = new javax.swing.JLabel();
        lblCitaId = new javax.swing.JLabel();
        lblMotivoConsulta = new javax.swing.JLabel();
        lblEnfermedad = new javax.swing.JLabel();
        lblanamnesis = new javax.swing.JLabel();
        lblAntecedentes = new javax.swing.JLabel();
        lblExamenFisico = new javax.swing.JLabel();
        lblEvolucion = new javax.swing.JLabel();
        lblTratamiento = new javax.swing.JLabel();
        lblDiagnostico = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtperId = new javax.swing.JTextField();
        txtNumPaciente = new javax.swing.JTextField();
        txtCitaID = new javax.swing.JTextField();
        txtMotivoConsulta = new javax.swing.JTextField();
        txtEnfermedad = new javax.swing.JTextField();
        txtAnamnesis = new javax.swing.JTextField();
        txtAntecedentes = new javax.swing.JTextField();
        txtExamenFisico = new javax.swing.JTextField();
        txtEvolucionMedica = new javax.swing.JTextField();
        txtTratamiento = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenerarHistoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGenerarHistoria.setText("Generar Historia");
        getContentPane().add(lblGenerarHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 180, 40));

        lblperId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblperId.setText("per Id:");
        getContentPane().add(lblperId, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 51, -1, -1));

        lblNumPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumPaciente.setText("Nun Paciente:");
        getContentPane().add(lblNumPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 89, -1, -1));

        lblCitaId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCitaId.setText("Cita Id:");
        getContentPane().add(lblCitaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 127, -1, -1));

        lblMotivoConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMotivoConsulta.setText("Motivo Consulta");
        getContentPane().add(lblMotivoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 165, -1, -1));

        lblEnfermedad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEnfermedad.setText("Enfermedad Actual:");
        getContentPane().add(lblEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 203, -1, -1));

        lblanamnesis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblanamnesis.setText("Anamnesis:");
        getContentPane().add(lblanamnesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 241, -1, -1));

        lblAntecedentes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAntecedentes.setText("Antecedentes:");
        getContentPane().add(lblAntecedentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 279, -1, -1));

        lblExamenFisico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExamenFisico.setText("Examen Fisico:");
        getContentPane().add(lblExamenFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 317, -1, -1));

        lblEvolucion.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblEvolucion.setText("Evolución Médica:");
        getContentPane().add(lblEvolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 355, -1, -1));

        lblTratamiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTratamiento.setText("Tratamiento:");
        getContentPane().add(lblTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 393, -1, -1));

        lblDiagnostico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDiagnostico.setText("Diagnostico:");
        getContentPane().add(lblDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 431, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 480, -1, -1));
        getContentPane().add(txtperId, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 51, 383, -1));
        getContentPane().add(txtNumPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 89, 383, -1));
        getContentPane().add(txtCitaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 127, 383, -1));
        getContentPane().add(txtMotivoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 165, 383, -1));
        getContentPane().add(txtEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 203, 383, -1));
        getContentPane().add(txtAnamnesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 241, 383, -1));
        getContentPane().add(txtAntecedentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 279, 383, -1));
        getContentPane().add(txtExamenFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 317, 383, -1));
        getContentPane().add(txtEvolucionMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 355, 383, -1));
        getContentPane().add(txtTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 393, 383, -1));
        getContentPane().add(txtDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 431, 383, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Historia.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Eventos">
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Asignación de variables">
        int varIdHistoria = 1;
        try {
             varIdHistoria = daoHistoria.contarFilas();
        } catch (SQLException ex) {
             Logger.getLogger(viewAsignarHorario.class.getName()).log(Level.SEVERE, null, ex);
        }
        int varPersonaId = Integer.parseInt(txtperId.getText());
        int varNumPaciente = Integer.parseInt(txtNumPaciente.getText());
        int varCitaMedicaId = Integer.parseInt(txtCitaID.getText());
        String varMotivoConsulta = txtMotivoConsulta.getText();
        String varEnfermedadActual = txtEnfermedad.getText();
        String varAnamnesis = txtAnamnesis.getText();
        String varAntecedentes = txtAntecedentes.getText();
        String varExamenFisico = txtExamenFisico.getText();
        String varEvolucionMedica = txtEvolucionMedica.getText();
        String varTratamiento = txtTratamiento.getText();
        String varDiagnostico = txtDiagnostico.getText();
        //</editor-fold>
        
        clsHistoriaClinica miHistoria = new clsHistoriaClinica(varIdHistoria, varPersonaId, varNumPaciente,
        varCitaMedicaId, varMotivoConsulta, varEnfermedadActual, varAnamnesis, varAntecedentes, varExamenFisico,
        varEvolucionMedica, varTratamiento, varDiagnostico);
        
        boolean varSeGenero = false;
         try {
             varSeGenero = daoHistoria.generarHistoria(miHistoria);
         } catch (SQLException ex) {
             Logger.getLogger(viewAsignarHorario.class.getName()).log(Level.SEVERE, null, ex);
         }
        if(varSeGenero == true)
        {
            JOptionPane.showMessageDialog(null, "Se genero la historia clinica correctamente correctamente.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No se pudo generar la historia clinica, por favor verifique los datos.");
        }        
    }//GEN-LAST:event_btnGuardarActionPerformed
    //</editor-fold> 
    
    //<editor-fold defaultstate="collapsed" desc="Starter">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewGenerarHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewGenerarHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewGenerarHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewGenerarHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewGenerarHistoria().setVisible(true);
            }
        });
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Componentes Swing">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAntecedentes;
    private javax.swing.JLabel lblCitaId;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblEnfermedad;
    private javax.swing.JLabel lblEvolucion;
    private javax.swing.JLabel lblExamenFisico;
    private javax.swing.JLabel lblGenerarHistoria;
    private javax.swing.JLabel lblMotivoConsulta;
    private javax.swing.JLabel lblNumPaciente;
    private javax.swing.JLabel lblTratamiento;
    private javax.swing.JLabel lblanamnesis;
    private javax.swing.JLabel lblperId;
    private javax.swing.JTextField txtAnamnesis;
    private javax.swing.JTextField txtAntecedentes;
    private javax.swing.JTextField txtCitaID;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtEnfermedad;
    private javax.swing.JTextField txtEvolucionMedica;
    private javax.swing.JTextField txtExamenFisico;
    private javax.swing.JTextField txtMotivoConsulta;
    private javax.swing.JTextField txtNumPaciente;
    private javax.swing.JTextField txtTratamiento;
    private javax.swing.JTextField txtperId;
    // End of variables declaration//GEN-END:variables
    //</editor-fold> 
}
