/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Control.*;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class ViewRegUsuario extends javax.swing.JFrame {
    
    private clsPersonaDAO objPersonaDAO = new clsPersonaDAO();
    private clsCuentaDAO objCuentaDAO = new clsCuentaDAO();
    private clsPacienteDAO objPacienteDAO = new clsPacienteDAO();
    
    public ViewRegUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCondicion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFecNac = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtDateChooser = new com.toedter.calendar.JDateChooser();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblmsgMail = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblmsgPass = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnIniSesion = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lblTitulo.setText("REGISTRO DE USUARIO");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 210, 30));

        lblCondicion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblCondicion.setForeground(new java.awt.Color(0, 0, 102));
        lblCondicion.setText("<html><body>Los campos marcados con (*) son obligatorios. <br> Todos los campos deben diligenciarse. </body></html>");
        getContentPane().add(lblCondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 70));

        lblNombre.setText("Nombre(s):*");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblApellido.setText("Apellidos(s):*");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblID.setText("Identificación:*");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblFecNac.setText("Fecha de Nacimiento:*");
        getContentPane().add(lblFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblTel.setText("Teléfono:");
        getContentPane().add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblMail.setText("E-mail:*");
        getContentPane().add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        lblAdress.setText("Dirección:");
        getContentPane().add(lblAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblPassword.setText("Contraseña:*");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, -1));
        getContentPane().add(txtDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 130, -1));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 180, -1));

        lblmsgMail.setText("Este será el usuario que lo identificará. ");
        getContentPane().add(lblmsgMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, -1));
        getContentPane().add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 180, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 180, -1));

        lblmsgPass.setText("<html><body>La contraseña debe contener <br> entre 4 y 16 caracteres. </body></html>");
        getContentPane().add(lblmsgPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 240, 30));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 80, 30));

        btnIniSesion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIniSesion.setText("Iniciar Sesion");
        btnIniSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 381, 100, 30));

        lblFondo.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Registro.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniSesionActionPerformed
        // se cierra esta ventana y se regresa a la misma instancia inicial de viewSesion
        this.dispose();
    }//GEN-LAST:event_btnIniSesionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        if(hayCamposVacios() == false){
            String varNombre = this.txtNombre.getText();
            String varApellido = this.txtApellido.getText();
            String varTelefono = this.txtTel.getText();
            String varEmail = this.txtEmail.getText();
            String varAdress = this.txtAdress.getText();
            char[] arrayC = this.txtPassword.getPassword();
            String varPassword = new String(arrayC);
            int varID = Integer.parseInt(this.txtID.getText());
            Date tempFecha = this.txtDateChooser.getDate();
            DateFormat f = new SimpleDateFormat("yyyy/MM/dd");
            String varFecha = f.format(tempFecha);

            clsPersona objPersona = new clsPersona(varID, varNombre, varApellido, varFecha, varTelefono, varEmail, varAdress);
            boolean RegPersona = objPersonaDAO.RegistrarPersona(objPersona);
            
            if(RegPersona){
                clsCuenta objCuenta = new clsCuenta(varEmail, varID, varPassword);
                boolean RegCuenta = objCuentaDAO.RegistrarCuenta(objCuenta);
                if(RegCuenta){
                    int numPaciente = -1;
                    try {
                        //obteniendo NumPaciente para asignar a nuevo paciente
                        numPaciente = objPacienteDAO.contarFilas();
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }

                    if (numPaciente != -1){
                        clsPaciente objPaciente = new clsPaciente(numPaciente, objPersona);
                        
                        boolean RegPaciente = objPacienteDAO.registrarPaciente(objPaciente);
                        if(RegPaciente){
                            LimpiarCampos();
                            JOptionPane.showMessageDialog(null, "Ha sido registrado con éxito. Ahora puede iniciar sesión.");
                            return;
                        }
                        else{
                        JOptionPane.showMessageDialog(null, "No se pudo registrar como paciente, por favor verifique los datos.");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado. Por favor intente más tarde");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se pudo registrar su cuenta, por favor verifique los datos.");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se pudo registrar sus datos, por favor verifiquelos.");
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Para continuar con el Registro LLene los campos solicitados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public void LimpiarCampos(){
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtID.setText("");
        this.txtDateChooser.setToolTipText("");
        this.txtTel.setText("");
        this.txtEmail.setText("");
        this.txtAdress.setText("");
        this.txtPassword.setText("");
    }
    
    public boolean hayCamposVacios(){
        boolean varEstanVacios = false;
        if(this.txtNombre.getText().trim().isEmpty()){
            txtNombre.requestFocus();
            varEstanVacios = true;
        }
        else if(this.txtApellido.getText().trim().isEmpty()){
            txtApellido.requestFocus();
            varEstanVacios = true;
        }
        else if(this.txtID.getText().trim().isEmpty()){
            txtID.requestFocus();
            varEstanVacios = true;
        }
        else if(this.txtEmail.getText().trim().isEmpty()){
            txtEmail.requestFocus();
            varEstanVacios = true;
        }
        else if(this.txtPassword.getText().trim().isEmpty()){
            txtNombre.requestFocus();
            varEstanVacios = true;
        }
        return varEstanVacios;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCondicion;
    private javax.swing.JLabel lblFecNac;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblmsgMail;
    private javax.swing.JLabel lblmsgPass;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtApellido;
    private com.toedter.calendar.JDateChooser txtDateChooser;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
