/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Control.clsCuentaDAO;
import Control.clsPersonaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juan jose
 */
public class ViewCuenta extends javax.swing.JFrame {
    
    /**
     * Creates new form ViewCuenta
     */
    public ViewCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConstraseña = new javax.swing.JLabel();
        lblEditarCuenta = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConstraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConstraseña.setText("Constraseña:");
        getContentPane().add(lblConstraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 66, -1, -1));

        lblEditarCuenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEditarCuenta.setText("EDITAR CUENTA");
        getContentPane().add(lblEditarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDireccion.setText("Direccion:");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 118, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 173, -1, -1));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 66, 183, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 118, 183, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 173, 183, -1));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 238, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 238, -1, -1));

        jLabel1.setBackground(new java.awt.Color(153, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Config.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Eventos">
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        clsCuentaDAO daoCuenta = new clsCuentaDAO();
        clsPersonaDAO daoPersona = new clsPersonaDAO();
        String varContraseña, varDireccion, varTelefono;
        boolean varSeActualizo = false;
        if(txtContrasenia.getText().equals(null) == false)
        {
            varContraseña = txtContrasenia.getText();
            varSeActualizo = daoCuenta.CambiarContraseña(varContraseña, viewSesion.atrIdUsuarioActual);        
            if(varSeActualizo == false)
            {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar la contraseña.");
            }
        }
        if(txtDireccion.getText().equals(null) == false)
        {
            varDireccion = txtDireccion.getText();
            varSeActualizo = daoPersona.CambiarDireccion(varDireccion, viewSesion.atrIdUsuarioActual);        
            if(varSeActualizo == false)
            {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar la direccion.");
            }
        }
        if(txtTelefono.getText().equals(null) == false)
        {
            varTelefono = txtTelefono.getText();
            varSeActualizo = daoPersona.CambiarTelefono(varTelefono, viewSesion.atrIdUsuarioActual);        
            if(varSeActualizo == false)
            {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el telefono.");
            }
        }
        if(varSeActualizo == true)
        {
            JOptionPane.showMessageDialog(null, "Se actualizaron los datos correctamente.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    //</editor-fold> 
    
    //<editor-fold defaultstate="collapsed" desc="Starter">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCuenta().setVisible(true);
            }
        });
    }
    //</editor-fold> 
    
    //<editor-fold defaultstate="collapsed" desc="Componentes Swing">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConstraseña;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEditarCuenta;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    //</editor-fold> 
}
