package Views;

import Control.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author Luis Arango
 * @author Yeferson Benavides
 * @author Juan José Rengifo
 */
public class viewRegMedico extends javax.swing.JFrame {

    /**
     * Creates new form viewRegMedico
     */
    public viewRegMedico() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegMedico = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblFechaNac = new javax.swing.JLabel();
        txtFechaNac = new com.toedter.calendar.JDateChooser();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblTarPro = new javax.swing.JLabel();
        txtTprofesional = new javax.swing.JTextField();
        lblEsp = new javax.swing.JLabel();
        lstEspecialidad = new javax.swing.JComboBox<>();
        lblExp = new javax.swing.JLabel();
        txtExperiencia = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblConsultorio = new javax.swing.JLabel();
        txtConsultorio = new javax.swing.JTextField();
        btnRegMedico = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegMedico.setBackground(new java.awt.Color(255, 255, 255));
        lblRegMedico.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblRegMedico.setText("Registrar Médico");
        getContentPane().add(lblRegMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setText("Nombres");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, -1));

        lblApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApellido.setText("Apellidos");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        lblFechaNac.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaNac.setText("Fecha de nacimiento");
        getContentPane().add(lblFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 180, -1));

        lblDNI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDNI.setText("DNI");
        getContentPane().add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, -1));

        lblTarPro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTarPro.setText("No. Tarjeta Profesional");
        getContentPane().add(lblTarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(txtTprofesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 180, -1));

        lblEsp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEsp.setText("Especialidad");
        getContentPane().add(lblEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        lstEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Ortopedia", "Medicina Interna", "Pediatria", "Cardiologia", "Anestesiologia", "Psiquiatria" }));
        getContentPane().add(lstEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));

        lblExp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblExp.setText("Experiencia");
        getContentPane().add(lblExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        getContentPane().add(txtExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 180, -1));

        lblAdress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAdress.setText("Dirección");
        getContentPane().add(lblAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 180, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 180, -1));

        lblTel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTel.setText("Teléfono");
        getContentPane().add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 180, -1));

        lblConsultorio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblConsultorio.setText("Consultorio");
        getContentPane().add(lblConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));
        getContentPane().add(txtConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 180, -1));

        btnRegMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegMedico.setText("Registrar");
        btnRegMedico.setToolTipText("");
        btnRegMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 80, 30));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 80, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/RegistroM edico.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegMedicoActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Asignación de variables">
        int varDNI = Integer.parseInt(txtDNI.getText());
        int varTjtaProf = Integer.parseInt(txtTprofesional.getText());
        String varNombre = txtNombre.getText();
        String varApellido = txtApellido.getText();
        Date tempFecha = txtFechaNac.getDate();
        DateFormat f= new SimpleDateFormat("yyyy/MM/dd");
        String varFecha = f.format(tempFecha);
        String varEspecialidad = lstEspecialidad.getSelectedItem().toString();
        //String varEspecialidad = txtEspecialidad.getText();
        Byte varExperiencia = Byte.parseByte(txtExperiencia.getText());
        String varDireccion = txtDireccion.getText();
        String varEmail = txtEmail.getText();
        int varConsultorio = Integer.parseInt(txtConsultorio.getText());
        String varTelefono = txtTelefono.getText();
//</editor-fold>
   
        clsPersona objPersona = new clsPersona(varDNI, varNombre, varApellido, varFecha, varTelefono, varEmail, varDireccion);
        daoPersona = new clsPersonaDAO();
        boolean varRegPersona = daoPersona.RegistrarPersona(objPersona);
        clsMedico objMedico = new clsMedico(objPersona,varTjtaProf, varEspecialidad, varExperiencia, varConsultorio);
        daoMedico = new clsMedicoDAO();
        boolean varRegMedico = daoMedico.registrarMedico(objMedico);
        clsCuenta objCuenta = new clsCuenta(varEmail, varDNI, Integer.toString(varTjtaProf));
        daoCuenta = new clsCuentaDAO();
        boolean varRegCuenta = daoCuenta.RegistrarCuenta(objCuenta);
        
        if(!(varRegPersona) || !(varRegMedico)){
            JOptionPane.showMessageDialog(null, "No se pudo registrar, por favor verifique los datos.");
        }
        else {
            String varMsg = "Médico Registrado con éxito.";
            if(!varRegCuenta){
                varMsg += "\nNo se registró una cuenta para el médico. Contacte con el administrador.";
            }
            LimpiarCampos();
            JOptionPane.showMessageDialog(null, varMsg);
        }
    }//GEN-LAST:event_btnRegMedicoActionPerformed

    public void LimpiarCampos(){
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtEmail.setText("");
        this.txtExperiencia.setToolTipText("");
        this.txtEmail.setText("");
        this.txtDNI.setText("");
        this.txtConsultorio.setText("");
        this.txtTelefono.setText("");
        this.txtTprofesional.setText("");
    }
    
    private clsMedicoDAO daoMedico;
    private clsPersonaDAO daoPersona;
    private clsCuentaDAO daoCuenta;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegMedico;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblConsultorio;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEsp;
    private javax.swing.JLabel lblExp;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegMedico;
    private javax.swing.JLabel lblTarPro;
    private javax.swing.JLabel lblTel;
    private javax.swing.JComboBox<String> lstEspecialidad;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtConsultorio;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExperiencia;
    private com.toedter.calendar.JDateChooser txtFechaNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTprofesional;
    // End of variables declaration//GEN-END:variables
}
